config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "reviews#index"
  resources :users, only: [:edit, :update]
  resources :reviews do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments
  with_options presence: true do
    validates :cafename
    validates :text
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reviews
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user

def set_current_user
  @current_user = User.find_by(id: session[:user_id])
end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/reviews/#{comment.review.id}"
  end
  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, review_id: params[:review_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @review = Review.new
  end

  def create
    Review.create(review_params)
  end

  def show
    @review = Review.find(params[:id])
    @comment = Comment.new
    @comments = @review.comments.includes(:user)
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
  end


  private
  def review_params
    params.require(:review).permit(:cafename,:address,:image,:text,:evaluation1,:evaluation2,:evaluation3,:evaluation4,:evaluation5,:existence1,:existence2,:existence3).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title CafeApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/posts/_header_view.html.haml
.header 
  .title
    cafe app
    %i.fas.fa-coffee
  .name-box
    .user-name 
      = current_user.name
    .box  
      .box_user_edit
        = link_to new_review_path(current_user) do
          = icon('fas','edit',class: 'icon')
      .box_cog
        = link_to edit_user_path(current_user) do
          = icon('fas', 'cog',class: 'icon')

app/views/posts/index.html.haml
.wrapper
  = render 'header_view'
  = render 'main_view'

app/views/reviews/_bar.html.haml
.navigation_bar
  .review 
    review 
  %form 
    .input-box
      %input{type: "text", placeholder: "キーワード検索", class: "input-text"}
    .form-btn
      %input{type: "submit", value: "検索", class: "send__btn"} 

app/views/reviews/_header_view.html.haml
.header 
  .title
    = link_to "cafe app", '/', class: "header__title--text"
    %i.fas.fa-coffee 
  .name-box
    .user-name 
      = current_user.name
    .box  
      .box_user_edit
        = link_to new_review_path(current_user) do
          = icon('fas','edit',class: 'icon')
      .box_cog
        = link_to edit_user_path(current_user) do
          = icon('fas', 'cog',class: 'icon')

app/views/reviews/_main_view.html.haml
.navigation_bar
  .review 
    review 
  %form 
    .input-box
      %input{type: "text", placeholder: "キーワード検索", class: "input-text"}
    .form-btn
      %input{type: "submit", value: "検索", class: "send__btn"} 

app/views/reviews/_review.html.haml
.review_main
  .post-box
    .post-box-left
      .cafe-name
        = review.cafename
      .address-box 
        %i.fas.fa-map-marker-alt
        .address
          = review.address
      .nickname 
        Review Writer : 
        = review.user.name
      %ul.existence
        %li.ex1  ※ Wi-Fi 
        = review.existence1
        %li.ex2  充電スペース 
        = review.existence2
        %li.ex3  喫煙スペース
        = review.existence3 
      .p1 1~5
      %ul.evaluation 
        %li.e1  勉強,仕事 
        = review.evaluation1
        %li.e2  オシャレ 
        = review.evaluation2
        %li.e3  デート 
        = review.evaluation3
        %li.e4  友達と,おしゃべり 
        = review.evaluation4
        %li.e5  食事 
        = review.evaluation5
    .post-box-right
      %ul.more_list
        %li
          = link_to '削除', "/reviews/#{review.id}", method: :delete
        %li
          = link_to '編集', "/reviews/#{review.id}/edit", method: :get
      .review_picture_font
        = link_to review_path(review.id) do
          %i.fas.fa-comment-alt
            %i.fas.fa-images     
      %p.date 
        = review.created_at.strftime("%Y年%m月%d日")

app/views/reviews/create.html.haml
.header 
  .title
    cafe app
    %i.fas.fa-coffee
  .name-box
    .user-name 
      = current_user.name
.navigation_bar
  .review 
    投稿完了
.contents.row
  .success
    %a.btn{:href => "/"} review一覧へ戻る

app/views/reviews/destroy.html.haml
.header 
  .title
    cafe app
    %i.fas.fa-coffee
  .name-box
    .user-name 
      = current_user.name
.navigation_bar
  .review 
    削除完了
.contents.row
  .success
    %a.btn{:href => "/"} review一覧へ戻る

app/views/reviews/edit.html.haml
.header 
  = render 'header_view'
.navigation_bar
  .review 
    review-write
= form_for @review do |f|
  .a
    = f.text_field :cafename, placeholder: "cafename"
  .b  
    = f.text_field :address, placeholder: "最寄駅"
    
  .c
    .c1
      %p1 wi-fi
      = f.text_field :existence1, placeholder: "あり/なし"
    .c2
      %p2 充電スペース
      = f.text_field :existence2, placeholder: "あり/なし"
    .c3
      %p3 喫煙スペース
      = f.text_field :existence3, placeholder: "あり/なし"
  .d
    .d1 
      %p4 勉強・仕事
      = f.text_field :evaluation1, placeholder: "1~5"
    .d2
      %p5 オシャレ
      = f.text_field :evaluation2, placeholder: "1~5"
    .d3
      %p6 デート
      = f.text_field :evaluation3, placeholder: "1~5"
    .d4
      %p7 友達と・おしゃべり
      = f.text_field :evaluation4, placeholder: "1~5"
    .d5
      %p8 食事
      = f.text_field :evaluation5, placeholder: "1~5"
  .e   
    = f.text_field :image, placeholder: "image"
  .f
    =f.text_area :text, placeholder: "review"
  .g
    =f.submit 'Send', class: "send__btn"

app/views/reviews/index.html.haml
.wrapper
  = render 'header_view'
  = render 'bar'
  = render @reviews
  = paginate(@reviews)

app/views/reviews/new.html.haml
.header 
  = render 'header_view'
.navigation_bar
  .review 
    review-write
= form_for @review do |f|
  .a
    = f.text_field :cafename, placeholder: "cafename"
  .b  
    = f.text_field :address, placeholder: "最寄駅"
    
  .c
    .c1
      %p1 wi-fi
      = f.text_field :existence1, placeholder: "あり/なし"
    .c2
      %p2 充電スペース
      = f.text_field :existence2, placeholder: "あり/なし"
    .c3
      %p3 喫煙スペース
      = f.text_field :existence3, placeholder: "あり/なし"
  .d
    .d1 
      %p4 勉強・仕事
      = f.text_field :evaluation1, placeholder: "1~5"
    .d2
      %p5 オシャレ
      = f.text_field :evaluation2, placeholder: "1~5"
    .d3
      %p6 デート
      = f.text_field :evaluation3, placeholder: "1~5"
    .d4
      %p7 友達と・おしゃべり
      = f.text_field :evaluation4, placeholder: "1~5"
    .d5
      %p8 食事
      = f.text_field :evaluation5, placeholder: "1~5"
  .e   
    = f.text_field :image, placeholder: "image"
  .f
    =f.text_area :text, placeholder: "review"
  .g
    =f.submit 'Send', class: "send__btn"
    
  




    
    

app/views/reviews/show.html.haml
.header 
  = render 'header_view'
.navigation_bar
  .review 
    review & photo
.review-a
  .text
    = @review.text
  .photo
    = @review.image
.comments
  - if current_user
    = form_for [@review, @comment] do |f|
      .a1
        = f.text_area :text, placeholder: "コメントする", rows: "2"
      .a2
        = f.submit "SEND"
  - else
    %strong
      %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
.commnts-u
  %h4 ＜コメント一覧＞
  - if @comments
    - @comments.each do |comment|
      %p
        %strong
          = link_to comment.user.name, "/users/#{comment.user_id}"
          ：
        = comment.text

app/views/reviews/update.html.haml
.header 
  .title
    cafe app
    %i.fas.fa-coffee
  .name-box
    .user-name 
      = current_user.name
.navigation_bar
  .review 
    編集完了
.contents.row
  .success
    %a.btn{:href => "/"} review一覧へ戻る

app/views/users/edit.html.haml
#account-page.account-page
  .header 
    .title
      cafe app
      %i.fas.fa-coffee
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'